pipeline:
  identifier: Harness_Take_Home
  name: Harness Take Home
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Git_source_repository
        repoName: harness-th
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        identifier: Build
        type: CI
        name: Build
        description: ""
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: BuildAndPushGAR_1
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  spec:
                    connectorRef: account.google_connector
                    host: us-central1-docker.pkg.dev
                    projectID: harness-take-home
                    imageName: gcr.io/harness-cicd-image
                    tags:
                      - <+pipeline.sequenceId>
