pipeline:
  identifier: Harness_Take_Home
  name: Harness Take Home
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Git_source_repository
        repoName: harness-th
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        identifier: Build
        type: CI
        name: Build
        description: ""
        spec:
          cloneCodebase: true
          platform:
            os: Linux
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build docker image
                  identifier: Build_docker_image
                  spec:
                    connectorRef: gcr
                    image: gcr.io/harness-take-home/harness-cicd-image:latest
                    shell: Sh
                    command: docker build -t gcr.io/harness-take-home/harness-cicd-image:latest .
              - step:
                  identifier: BuildAndPushGAR_1
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  spec:
                    connectorRef: gcr
                    host: us-central1-docker.pkg.dev
                    projectID: harness-take-home
                    imageName: gcr.io/harness-cicd-image
                    tags:
                      - <+pipeline.sequenceId>
